skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
penne_bank_app = "FTvCUaTYSVNYUwLWk4yxgvW3Y81e1HjWD8nLxbxxKt5T"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
